Migrate hardcoded dependencies to version catalog
ARK-Builders/ARK-Memo pull request #82
Opened 2024-10-28 16:00 UTC by tuancoltech

Migrate hardcoded dependencies to version catalog.

`[Gradle version catalogs](https://docs.gradle.org/current/userguide/platforms.html) enable you to add and maintain dependencies and plugins in a scalable way. Using Gradle version catalogs makes managing dependencies and plugins easier when you have [multiple modules](https://developer.android.com/topic/modularization). Instead of hardcoding dependency names and versions in individual build files and updating each entry whenever you need to upgrade a dependency, you can create a central version catalog of dependencies that various modules can reference in a type-safe way with Android Studio assistance.`

https://app.asana.com/0/1207819682524134/1208308884950165
https://developer.android.com/build/migrate-to-catalogs

2024-11-04 08:59 UTC, shubertm requested changes

2024-11-04 08:59 UTC, shubertm commented on app/build.gradle
> +    implementation(libraries.viewbinding.property.delegate)
```suggestion
implementation(libraries.viewbinding.property.delegate.noreflection)
```

2024-11-04 08:59 UTC, shubertm commented on app/build.gradle
> +    implementation(libraries.arkbuilder.arkfilepicker)
```suggestion
implementation(libraries.arkbuilders.arkfilepicker)
```

2024-11-04 08:59 UTC, shubertm commented on app/build.gradle
> +    implementation(libraries.arkbuilder.arklib)
```suggestion
implementation(libraries.arkbuilders.arklib)
```

2024-11-04 08:59 UTC, shubertm commented on gradle/libs.versions.toml
> +arkbuilder-arkfilepicker = { group = "dev.arkbuilders", name = "arkfilepicker", version.ref = "arkFilepicker" }
```suggestion
arkbuilders-arkfilepicker = { group = "dev.arkbuilders", name = "arkfilepicker", version.ref = "arkFilepicker" }
```

2024-11-04 08:59 UTC, shubertm commented on gradle/libs.versions.toml
> +arkbuilder-arklib = { group = "dev.arkbuilders", name = "arklib", version.ref = "arkLib" }
```suggestion
arkbuilders-arklib = { group = "dev.arkbuilders", name = "arklib", version.ref = "arkLib" }
```

2024-11-04 08:59 UTC, shubertm commented on gradle/libs.versions.toml
> +arklib = { group = "dev.arkbuilders", name = "arklib", version.ref = "arkLib" }
This is redundant, should be removed

2024-11-04 08:59 UTC, shubertm commented on gradle/libs.versions.toml
> +viewbinding-property-delegate = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "viewbindingPropertyDelegate" }
```suggestion
viewbinding-property-delegate-noreflection = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "viewbindingPropertyDelegate" }
```

2024-11-08 01:28 UTC, hieuwu approved these changes

2024-11-10 10:23 UTC, tuancoltech commented
@shubertm This PR's branch is managed in rebase-based strategy.
Please don't push merge commit to it.
I'll be hard-resetting it now.

2024-11-10 12:30 UTC, shubertm commented
> @shubertm This PR's branch is managed in rebase-based strategy. Please don't push merge commit to it. I'll be hard-resetting it now.

So, would you please fix all issues I requested. Not all are fixed.

2024-11-11 05:48 UTC, tuancoltech commented
> > @shubertm This PR's branch is managed in rebase-based strategy. Please don't push merge commit to it. I'll be hard-resetting it now.
> 
> So, would you please fix all issues I requested. Not all are fixed.

@shubertm You mean the changes you requested above?
I think all of them were fixed.
Could you do a git pull --rebase and check again?

2024-11-11 08:17 UTC, shubertm commented
> > > @shubertm This PR's branch is managed in rebase-based strategy. Please don't push merge commit to it. I'll be hard-resetting it now.
> > 
> > 
> > So, would you please fix all issues I requested. Not all are fixed.
> 
> @shubertm You mean the changes you requested above? I think all of them were fixed. Could you do a git pull --rebase and check again?

Yes, the redundant dependency `arklib` is still there

2024-11-11 15:15 UTC, tuancoltech commented
> > > > @shubertm This PR's branch is managed in rebase-based strategy. Please don't push merge commit to it. I'll be hard-resetting it now.
> > > 
> > > 
> > > So, would you please fix all issues I requested. Not all are fixed.
> > 
> > 
> > @shubertm You mean the changes you requested above? I think all of them were fixed. Could you do a git pull --rebase and check again?
> 
> Yes, the redundant dependency `arklib` is still there

@shubertm `arklib` is being used in `app/build.gradle` line 93.

2024-11-12 02:42 UTC, shubertm commented
Yes, but in libs.versions.toml it is defined twice, line 39 and 64

2024-11-12 05:34 UTC, tuancoltech commented
> Yes, but in `libs.versions.toml` it is defined twice, line 39 and 64

That's a good catch!
Removed it now.

2024-11-12 16:21 UTC, hieuwu approved these changes

2024-11-13 05:41 UTC, merged